pcengines-seabios-24.05.00.01: add keys
3mdeb/3mdeb-secpack pull request #140
Opened 2024-06-15 23:11 UTC by pietrushnic

2024-06-17 09:05 UTC, miczyg1 requested changes

2024-06-17 09:05 UTC, miczyg1 commented on dasharo/pcengines_apu2/dasharo-release-24.05.00.x-for-pc-engines-signing-key.asc
@pietrushnic why is it binary? IIRC all keys on the repo are armored

2024-06-17 11:59 UTC, pietrushnic commented on dasharo/pcengines_apu2/dasharo-release-24.05.00.x-for-pc-engines-signing-key.asc
oops, aparently wrong params during export, let me fix that

2024-06-17 14:49 UTC, pietrushnic commented on dasharo/pcengines_apu2/dasharo-release-24.05.00.x-for-pc-engines-signing-key.asc
@miczyg1 force pushed the fix: https://github.com/3mdeb/3mdeb-secpack/pull/140/commits/9a764b80172e18b0bac46aaabd558c195a3d0d83

BTW, we could probably add such a check into pre-commit. Not sure how to do that or where to report, @macpijan ?

2024-06-17 14:59 UTC, macpijan commented on dasharo/pcengines_apu2/dasharo-release-24.05.00.x-for-pc-engines-signing-key.asc
Not sure what the problem was exactly, but if you have two cases: "good" and "bad" you can make a script that exits with non-zero exit code on "bad" key file and add it as a local hook. Example: https://github.com/3mdeb/conferences/blob/master/.pre-commit-config.yaml#L51

2024-06-19 10:22 UTC, miczyg1 commented on dasharo/pcengines_apu2/dasharo-release-24.05.00.x-for-pc-engines-signing-key.asc
Checking for `-----BEGIN PGP PUBLIC KEY BLOCK-----` presence should be sufficient.

But also I would add a presence check for `-----BEGIN PGP PRIVATE KEY BLOCK-----` and fail if found. Not sure though how we can prevent adding private binary keys to the local repo... Maybe there are some utilities to do so as well.

2024-06-19 10:22 UTC, miczyg1 approved these changes

2024-06-19 13:58 UTC, macpijan commented on dasharo/pcengines_apu2/dasharo-release-24.05.00.x-for-pc-engines-signing-key.asc
This is already solved: https://github.com/3mdeb/3mdeb-secpack/blob/master/.pre-commit-config.yaml#L21

2024-06-19 23:21 UTC, pietrushnic commented on dasharo/pcengines_apu2/dasharo-release-24.05.00.x-for-pc-engines-signing-key.asc
created issue for that, hopefully someone will have time to implement it at some point: https://github.com/3mdeb/3mdeb-secpack/issues/141

2024-06-19 23:22 UTC, pietrushnic commented on dasharo/pcengines_apu2/dasharo-release-24.05.00.x-for-pc-engines-signing-key.asc
ideally if roadmap would be pushed every time we touching this repo

2024-06-19 23:22 UTC, pietrushnic commented on dasharo/pcengines_apu2/dasharo-release-24.05.00.x-for-pc-engines-signing-key.asc
@miczyg1 please resolve if you think thread is done and merge

2024-06-20 09:13 UTC, merged